### ISSUE TITLE
Why not use `mktemp`

### ISSUE THREAD

**Issue by emilbayes** [mafintosh/tmpdir-tab#1]
I'm interested in why you chose to generate your own temp dir instead of using the Unix `mktemp` command?

**Comment by nealrs** [comment]
@emilbayes i'm looking at the `mktemp` man page and I don't think it has cleanup on exit.

**edit:** think i misinterpreted your point. nm!!

**Comment by mafintosh** [comment]
thanks! didn't know about `mktemp`. 1.1.0 uses that now
